from enum import Enum


class CodiusVariables(Enum):
    CODIUS_HYPER_SOCKET = 'CODIUS_HYPER_SOCKET',
    CODIUS_HYPER_NOOP = 'CODIUS_HYPER_NOOP',
    CODIUS_PORT = 'CODIUS_PORT',
    CODIUS_PUBLIC_URI = 'CODIUS_PUBLIC_URI',
    CODIUS_MAX_MEMORY_FRACTION = 'CODIUS_MAX_MEMORY_FRACTION',
    CODIUS_ADDITIONAL_HOST_INFO = 'CODIUS_ADDITIONAL_HOST_INFO',
    CODIUS_BOOTSTRAP_PEERS = 'CODIUS_BOOTSTRAP_PEERS',
    CODIUS_SELF_TEST_INTERVAL = 'CODIUS_SELF_TEST_INTERVAL',
    CODIUS_SELF_TEST_RETRIES = 'CODIUS_SELF_TEST_RETRIES'

    @classmethod
    def has_value(cls, value):
        return any(value == item.value for item in cls)
